AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 6
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: post
